Repository liferay/liferay-js-themes-toolkit, pull requests merged in 2019-04, with the labels that each got.

#272 doc: remove stale references to Visual Studio (#271)
  packages/generator-liferay-theme/README.md
Labels: 9.x, documentation

#273 doc: remove stale references to Visual Studio (#271)
  packages/generator-liferay-theme/README.md
Labels: 8.x, documentation

#275 feat: automatically prefetch tags before running changelog generator
  scripts/changelog.js
Labels: 9.x, enhancement

#276 fix: make it harder to accidentally produce duplicate entries in changelog
  scripts/changelog.js
Labels: bug

#278 feat: print watch info when starting watch (#277)
  packages/liferay-theme-tasks/tasks/watch.js
Labels: 9.x, enhancement

#279 feat: print watch info when starting watch (v8.x) (#277)
  packages/liferay-theme-tasks/tasks/watch.js
Labels: 8.x, enhancement

#281 fix: broken format script in package.json
  .eslintrc.js
  package.json
  packages/generator-liferay-theme/.yo-rc.json
Labels: 8.x, bug

#283 chore: Update references to "DXP" in user-facing messages (9.x) (#280)
  CHANGELOG.md
  README.md
  packages/generator-liferay-theme/generators/common/messages.js
Labels: 9.x, chore, documentation

#282 chore: Update references to "DXP" in user-facing messages (8.x) (#280)
  CHANGELOG.md
  README.md
Labels: 8.x, chore, documentation

#287 fix: silent failures when using autoprefixer (9.x) (#274)
  packages/liferay-theme-tasks/package.json
  packages/liferay-theme-tasks/tasks/build.js
  packages/liferay-theme-tasks/tasks/build/compile-css.js
  yarn.lock
Labels: 9.x, bug

#288 fix: silent failures when using autoprefixer (8.x) (#274)
  packages/liferay-theme-tasks/package.json
  packages/liferay-theme-tasks/tasks/build.js
  packages/liferay-theme-tasks/tasks/build/compile-css.js
  yarn.lock
Labels: 8.x, bug

#289 feat: add ability to config PostCSS plug-ins (9.x) (#126)
  packages/liferay-theme-tasks/lib/util.js
  packages/liferay-theme-tasks/package.json
  packages/liferay-theme-tasks/tasks/build/compile-css.js
Labels: 9.x, bug, chore, enhancement

#290 feat: add ability to config PostCSS plug-ins (8.x) (#126)
  packages/liferay-theme-tasks/lib/util.js
  packages/liferay-theme-tasks/package.json
  packages/liferay-theme-tasks/tasks/build/compile-css.js
Labels: 8.x, bug, chore, enhancement

#293 doc: remove Gulp entry from version table (v8.x)
  README.md
Labels: 8.x, chore, documentation

#294 doc: remove Gulp entry from version table (v9.x)
  README.md
Labels: 9.x, chore, documentation

#301 feat: auto-deploy when starting `gulp watch` (8.x) (#291)
  packages/generator-liferay-theme/CHANGELOG.md
  packages/liferay-theme-tasks/CHANGELOG.md
  packages/liferay-theme-tasks/tasks/__tests__/watch.test.js
  packages/liferay-theme-tasks/tasks/deploy.js
  packages/liferay-theme-tasks/tasks/watch.js
Labels: 8.x, chore, enhancement

#306 feat: teach theme tasks to accept --sass-include-paths option (#305)
  packages/liferay-theme-tasks/README.md
  packages/liferay-theme-tasks/lib/__tests__/options.test.js
  packages/liferay-theme-tasks/lib/options.js
  packages/liferay-theme-tasks/lib/prompts/extend_prompt.js
  packages/liferay-theme-tasks/lib/util.js
  packages/liferay-theme-tasks/plugin/lib/options.js
  packages/liferay-theme-tasks/plugin/test/index.js
  packages/liferay-theme-tasks/tasks/build/compile-css.js
Labels: 9.x, enhancement

#316 fix: make "watch" mode work with portal gzipped (#311)
  packages/liferay-theme-tasks/tasks/watch.js
Labels: 8.x, bug

#317 doc: add v7 to the compatibility table (9.x) (#313)
  README.md
Labels: 9.x, documentation

#318 doc: add v7 to the compatibility table (#313)
  README.md
Labels: 8.x, documentation

#322 fix: invalid "this" in deploy-live:war task (9.x)
  packages/liferay-theme-tasks/lib/war_deployer.js
Labels: 9.x, bug

#323 fix: invalid "this" in deploy-live:war task (8.x)
  packages/liferay-theme-tasks/lib/war_deployer.js
Labels: 8.x, bug

#325 perf: avoid unnecessary buffering of responses in watch mode (#324)
  packages/liferay-theme-tasks/tasks/watch.js
Labels: 9.x, performance

#326 perf: avoid unnecessary buffering of responses in watch mode (#324)
  packages/liferay-theme-tasks/tasks/watch.js
Labels: 8.x, performance
