Repository liferay/liferay-js-themes-toolkit, pull requests merged in 2019-06, with the labels that each got.

#342 chore: Update theme dependencies for Liferay 7.2 release (#341)
  packages/liferay-theme-tasks/lib/devDependencies.js
Labels: 9.x, chore

#343 feat: add a runtime NodeJS version check (#339)
  packages/liferay-theme-tasks/index.js
  packages/liferay-theme-tasks/lib/checkNodeVersion.js
Labels: 9.x, enhancement

#344 feat: add a runtime NodeJS version check (#339)
  packages/liferay-theme-tasks/index.js
  packages/liferay-theme-tasks/lib/checkNodeVersion.js
Labels: 8.x, enhancement

#345 fix(tasks): non-CSS/JS file changes break CSS when using "watch" (#340)
  packages/liferay-theme-tasks/tasks/build/compile-css.js
  packages/liferay-theme-tasks/tasks/watch.js
Labels: 9.x, bug

#346 fix(tasks): non-CSS/JS file changes break CSS when using "watch" (#340)
  packages/liferay-theme-tasks/tasks/build/compile-css.js
  packages/liferay-theme-tasks/tasks/watch.js
Labels: 8.x, bug

#353 chore: strictly peg dependency versions (#352)
  packages/liferay-theme-tasks/lib/devDependencies.js
Labels: 9.x, chore

#355 docs: indicate the use of `--tag` when publishing
  CONTRIBUTING.md
Labels: 8.x, documentation

#357 docs: clarify that only some packages need to be tagged
  CONTRIBUTING.md
Labels: 8.x, documentation

#358 fix: prevent proxy errors from killing the watcher
  packages/liferay-theme-tasks/tasks/watch.js
Labels: 9.x, bug

#360 fix: prevent proxy errors from killing the watcher (8.x)
  packages/liferay-theme-tasks/tasks/watch.js
Labels: 8.x, bug

#332 feat: teach `gulp extend` to accept a package URL (8.x) (#266)
  packages/liferay-theme-tasks/lib/prompts/__tests__/extend_prompt.test.js
  packages/liferay-theme-tasks/lib/prompts/__tests__/kickstart_prompt.test.js
  packages/liferay-theme-tasks/lib/prompts/__tests__/prompt_util.test.js
  packages/liferay-theme-tasks/lib/prompts/extend_prompt.js
  packages/liferay-theme-tasks/lib/prompts/kickstart_prompt.js
  packages/liferay-theme-tasks/lib/prompts/url_package_prompt.js
  packages/liferay-theme-tasks/lib/theme_finder.js
Labels: 8.x, enhancement

#333 feat: teach `gulp extend` to accept a package URL (9.x) (#266)
  packages/liferay-theme-tasks/lib/prompts/__tests__/extend_prompt.test.js
  packages/liferay-theme-tasks/lib/prompts/__tests__/kickstart_prompt.test.js
  packages/liferay-theme-tasks/lib/prompts/__tests__/prompt_util.test.js
  packages/liferay-theme-tasks/lib/prompts/extend_prompt.js
  packages/liferay-theme-tasks/lib/prompts/kickstart_prompt.js
  packages/liferay-theme-tasks/lib/prompts/url_package_prompt.js
  packages/liferay-theme-tasks/lib/theme_finder.js
Labels: 9.x, enhancement
